// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Visual.Models.Database;

#nullable disable

namespace Visual.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429193624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Visual.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn Node.js, Express, and MongoDB from scratch.",
                            Hours = 60,
                            Instructor = "Alaa Ahmed",
                            Price = 150.00m,
                            Title = "Full Stack Web Development"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Build professional desktop and web applications.",
                            Hours = 45,
                            Instructor = "Ahmed Ali",
                            Price = 120.00m,
                            Title = "Mastering C# and .NET"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design beautiful user interfaces with Figma.",
                            Hours = 30,
                            Instructor = "Sara Mohamed",
                            Price = 90.00m,
                            Title = "UI/UX Design Fundamentals"
                        });
                });

            modelBuilder.Entity("Visual.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 22,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed1@gmail.com",
                            Name = "Ahmed Ali",
                            Phone = "01000000001"
                        },
                        new
                        {
                            Id = 2,
                            Age = 20,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara2@gmail.com",
                            Name = "Sara Mohamed",
                            Phone = "01000000002"
                        },
                        new
                        {
                            Id = 3,
                            Age = 23,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar3@gmail.com",
                            Name = "Omar Hassan",
                            Phone = "01000000003"
                        },
                        new
                        {
                            Id = 4,
                            Age = 21,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mona4@gmail.com",
                            Name = "Mona Ahmed",
                            Phone = "01000000004"
                        },
                        new
                        {
                            Id = 5,
                            Age = 24,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khaled5@gmail.com",
                            Name = "Khaled Ali",
                            Phone = "01000000005"
                        },
                        new
                        {
                            Id = 6,
                            Age = 19,
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nour6@gmail.com",
                            Name = "Nour Tarek",
                            Phone = "01000000006"
                        },
                        new
                        {
                            Id = 7,
                            Age = 25,
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef7@gmail.com",
                            Name = "Youssef Adel",
                            Phone = "01000000007"
                        },
                        new
                        {
                            Id = 8,
                            Age = 22,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "heba8@gmail.com",
                            Name = "Heba Mostafa",
                            Phone = "01000000008"
                        },
                        new
                        {
                            Id = 9,
                            Age = 26,
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tamer9@gmail.com",
                            Name = "Tamer Saad",
                            Phone = "01000000009"
                        },
                        new
                        {
                            Id = 10,
                            Age = 20,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laila10@gmail.com",
                            Name = "Laila Sameh",
                            Phone = "01000000010"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
