// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Visual.Models.Database;

#nullable disable

namespace Visual.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429205619_AddMoreSeedBooks")]
    partial class AddMoreSeedBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Visual.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CopiesAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            CopiesAvailable = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Software Engineering",
                            PublishedYear = 2008,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Hunt",
                            CopiesAvailable = 3,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Software Engineering",
                            PublishedYear = 1999,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "James Clear",
                            CopiesAvailable = 5,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Self Development",
                            PublishedYear = 2018,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Cal Newport",
                            CopiesAvailable = 4,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Productivity",
                            PublishedYear = 2016,
                            Title = "Deep Work"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Erich Gamma",
                            CopiesAvailable = 2,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Software Engineering",
                            PublishedYear = 1994,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Martin Fowler",
                            CopiesAvailable = 3,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Software Engineering",
                            PublishedYear = 2018,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Francesc Miralles",
                            CopiesAvailable = 6,
                            CreatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Wellbeing",
                            PublishedYear = 2017,
                            Title = "Ikigai"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Eric Ries",
                            CopiesAvailable = 3,
                            CreatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Business",
                            PublishedYear = 2011,
                            Title = "The Lean Startup"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Yuval Noah Harari",
                            CopiesAvailable = 4,
                            CreatedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "History",
                            PublishedYear = 2014,
                            Title = "Sapiens"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
